### ISSUE TITLE
SQL Connection Pool seems to max out often

### ISSUE THREAD

**Issue by janpieterz** [Particular/NServiceBus.SqlServer#286] opened 2016-08-07 14:54 UTC
I've been using this, running on a hosted Azure SQL. It seems to quite often run out of its connections. I have been making more and more code changes to look for ways I am contributing to it, and as far as I know (using one SqlConnection in mode ```DependencyLifecycle.InstancePerUnitOfWork```) I should hardly be. Besides that I don't really use any SqlConnection, but I do use NServiceBus NHibernate persistence (same sql server) and then also the SqlServer transport.

I am wondering if Azure hosted SqlServer is in any way a supported platform / you guys take it into account? We're using SqlServer in particular right now because we also use it for application data, and this will become an installed package (no control from us at all). Third parties tend to prefer having less components to care for, hence why (generally I use Azure ServiceBus or RabbitMq as transports).

Thoughts? We'll generally host it with customers on a local SqlServer, but would like to support the Azure Sql case too.

**Comment by MarcinHoppe** [comment] 2016-08-08 12:43
@janpieterz Thanks for reaching out.

We definitely take the Azure SQL Database into account. The Azure SQL Database service has a throttling mechanism to cope with excessive resource consumption and it may happen that after exceeding a resource usage limit for a particular service tier and performance level you might encounter database connection problems.

What is the exact error / exception that you are seeing? 

As always, a standalone reproduction of this issue would be ideal.

**Comment by janpieterz** [comment] 2016-08-08 13:08
Hi @MarcinHoppe , Good to know it's being taken into account.

Error messages I received certainly indicate max pool size being reached:
```
System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
```
Oddly though, there was hardly anything happening from my side (one connection per UnitOfWork) and only NHibernate Persistence and SqlServer Transport running. It was running on a relatively small db (S0). It seemed to happen only after a while too, so almost like there was some kind of connection slip that wasn't closed correctly, while the pool grew? My knowledge of pooling isn't that high level, so I might be off.

Essentially what I did was receiving messages, that had needed certain storages which depended upon an SqlConnection. At tops 2 storages were used per handler, and I confirmed only one SqlConnection being created in my code per message. The Saga was used heavily, but enabling the NHibernate Azure SQL Driver didn't make a difference, hence me asking here to see how/if this was taken into account ;)

I've currently migrated our staging to a local hosted SQL so there's certainly no urgency, and testing it breaking  also took quite a while (sometimes ~2 days of relative stable load). I'll try to make a reproduction when I got some time (2+ weeks)!

**Comment by MarcinHoppe** [comment] 2016-08-09 13:56
@janpieterz Do you have a full stack trace for this exception?

Also, did you modify the connection pool size in any way or are you using the default 100 connections?

Connection pool size can be adjusted using `Max Pool Size` and `Min Pool Size` connection string parameters. Have you tried adjusting these?

**Comment by janpieterz** [comment] 2016-08-10 06:12
Sure! Added them below. 
I thought (possibly incorrectly) that Azure Max Pool size for these S0 insances is even lower than 100, so didn't bother changing them at the time (there was of course the urge to get it sorted ASAP).

If below exceptions don't give you more info (they just seem to signal that it is wrong, to me), I'll try and knock a repro up. It almost seems to me like there is a 'connection leak' somewhere but that might be my naive understanding. An added bit of information can be that the one of the message handlers that were invoked took probably 2/3 minutes to finish up.



```
System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Configuration\SqlConnectionFactory.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.QueuePeeker.<Peek>d__1.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Receiving\QueuePeeker.cs:line 21
```

Another one for the timeout (this one seems to appear ~once for every three peeks):
```
NHibernate.TransactionException: Begin failed with SQL exception ---> System.Data.SqlClient.SqlException: Database 'intreba-enm' on server 'intreba' is not currently available.  Please retry the connection later.  If the problem persists, contact customer support, and provide them the session tracing ID of '9CB662FF-89F2-4339-A341-7D5B4E4C5D72'.
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at NHibernate.Connection.DriverConnectionProvider.GetConnection()
   at NHibernate.AdoNet.ConnectionManager.GetConnection()
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
   --- End of inner exception stack trace ---
   at NHibernate.Transaction.AdoTransaction.Begin(IsolationLevel isolationLevel)
   at NHibernate.Impl.StatelessSessionImpl.BeginTransaction(IsolationLevel isolationLevel)
   at NServiceBus.TimeoutPersisters.NHibernate.TimeoutPersister.GetNextChunk(DateTime startSlice) in C:\Build\src\NServiceBus.NHibernate\TimeoutPersisters\TimeoutPersister.cs:line 40
   at NServiceBus.ExpiredTimeoutsPoller.<SpinOnce>d__11.MoveNext() in C:\Build\src\NServiceBus.Core\DelayedDelivery\TimeoutManager\ExpiredTimeoutsPoller.cs:line 98
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ExpiredTimeoutsPoller.<InnerPoll>d__10.MoveNext() in C:\Build\src\NServiceBus.Core\DelayedDelivery\TimeoutManager\ExpiredTimeoutsPoller.cs:line 85
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.ExpiredTimeoutsPoller.<Poll>d__9.MoveNext() in C:\Build\src\NServiceBus.Core\DelayedDelivery\TimeoutManager\ExpiredTimeoutsPoller.cs:line 67
```

Then an interesting one for the Sql Receive operation:
```
System.InvalidOperationException: This SqlTransaction has completed; it is no longer usable.
   at System.Data.SqlClient.SqlTransaction.ZombieCheck()
   at System.Data.SqlClient.SqlTransaction.Rollback()
   at NServiceBus.Transport.SQLServer.ReceiveWithSendsAtomicWithReceiveTransaction.<ReceiveMessage>d__1.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Receiving\ReceiveWithSendsAtomicWithReceiveTransaction.cs:line 69
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.MessagePump.<InnerReceive>d__6.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Receiving\MessagePump.cs:line 153
```

And the expired message purger throws some too:
```
System.Data.SqlClient.SqlException (0x80131904): A severe error occurred on the current command.  The results, if any, should be discarded.
A severe error occurred on the current command.  The results, if any, should be discarded.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<PurgeBatchOfExpiredMessages>d__13.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Queuing\TableBasedQueue.cs:line 147
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ExpiredMessagesPurger.<Purge>d__7.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Receiving\ExpiredMessagesPurger.cs:line 37
ClientConnectionId:4ae0fc3d-53da-40be-a35d-84769854e52e
ClientConnectionId before routing:c2fdc3a1-a589-45b0-afb1-8c0c3a4032b7
Routing Destination:c24b0f19c05f.tr11.westeurope1-a.worker.database.windows.net,11026
```

**Comment by MarcinHoppe** [comment] 2016-08-10 13:51
@janpieterz Some of these stack traces represent exceptions that have been thrown during transaction rollback. This is something we are aware of and that is fixed now on the release branch. We will release a bug fix for this in 3.0.0-beta0004 build (due soon).

As to the connection pool limits, a reproduction would be a huge help.

**Comment by MarcinHoppe** [comment] 2016-08-18 09:25
@janpieterz We have just released 3.0.0-beta0005 to NuGet that should alleviate the throw-on-rollback problem (triggering the circuit breaker instead of a retry).

If you need help in upgrading, just let me know.

**Comment by janpieterz** [comment] 2016-08-18 09:33
@MarcinHoppe cheers for the heads up! I was already running on beta0005 since 15-08 from the Particular MyGet feed (https://www.myget.org/F/particular/).
Are there changes compared to that one on the particular feed? We've for this one changed the underlying storage to a self-hosted SQL but have indeed noticed improvement in connections to that one too, which is great! :)

I'll spend time next week trying to setup a replication of the previous problem with Azure SQL (using the newest packages of course). I'll let you know about it on this issue. If it is still occurring (I'll use the same patterns of connections etc) I'll publish the repo and we can dive deeper, otherwise I'll report and we can close this one.

**Comment by MarcinHoppe** [comment] 2016-08-18 11:18
@janpieterz The Beta5 package on the MyGet feed and now on NuGet is the same package, no differenced whatsoever.

Feel free to pull me in if you have any problems with the transport.

**Comment by janpieterz** [comment] 2016-08-22 07:17
Interestingly, just yesterday after running continuously since Friday, it started (local SQL installed) to bork up again.

Last logged message:
```
2016-08-22 00:38:08 (NServiceBus.Transport.SQLServer.RepeatedFailuresOverTimeCircuitBreaker) [Warning] The circuit breaker for "ReceiveText" will now be triggered
2016-08-22 00:38:08 (NServiceBus) [Fatal] Failed to receive from Server.Timeouts@[transport]
System.InvalidOperationException: Timeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.
   at System.Data.Common.ADP.ExceptionWithStackTrace(Exception e)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Configuration\SqlConnectionFactory.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ReceiveWithNativeTransaction.<ReceiveMessage>d__1.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Receiving\ReceiveWithNativeTransaction.cs:line 56
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.MessagePump.<InnerReceive>d__6.MoveNext() in C:\Build\src\NServiceBus.SqlServer\Receiving\MessagePump.cs:line 153
```
Windows event log:
```
Application: NServiceBus.Host.exe
Framework Version: v4.0.30319
Description: The application requested process termination through System.Environment.FailFast(string message).
Message: The following critical error was encountered by NServiceBus:NServiceBus is shutting down.
Stack:
   at System.Environment.FailFast(System.String)
   at NServiceBus.GenericHost+<OnCriticalError>d__7.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[[NServiceBus.GenericHost+<OnCriticalError>d__7, NServiceBus.Host, Version=7.0.0.0, Culture=neutral, PublicKeyToken=9fc386479f8a226c]](<OnCriticalError>d__7 ByRef)
   at NServiceBus.GenericHost.OnCriticalError(NServiceBus.ICriticalErrorContext)
   at System.Threading.Tasks.Task`1[[System.__Canon, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]].InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

I'm working on a repro where I hope to put all the concepts down similarly (saga with a couple of stages, other schedules etc). It might just be the case of me keeping connections open on my side somewhere and slowly leaking more and more ;)

**Comment by janpieterz** [comment] 2016-08-22 16:21
(for others: code and complementing data has been provided so the investigation can go a bit quicker).

On another note:
I just investigated a moment where a saga somehow stayed in exactly the same state forever, until I manually removed this. The saga always schedules a timeout, and ensures this that even if the underlying event handlers somehow never reach their return messages, it should close itself. 

The logs show that the timeout and the message come through the `NServiceBus.RoutingToDispatchConnector` but after that seem to disappear. No mention of the message id ever occurs again, the saga stayed in the 'intermediate' state and the message handler never logs its arrival. The process crashed presumably (event logs doesn't go back that far), since a restart is logged ~8 minutes after. Nothing ever happens with those messages again and the saga hangs indefinitely. There's a lot of logging around this concerning the connections, so I presume it was somehow able to mark the incoming message as done without concerning itself to send out the outgoing message yet. 
Nothing ever happens with those messages again and the saga hangs indefinitely. There's a lot of logging around this concerning the connections, so I presume it was somehow able to mark the incoming message as done without concerning itself to send out the outgoing message yet. 

The cause might be a combination of a configuration setting on my side and the connection pool, although the transport is set to `SendsAtomicWithReceive` which to me reads like this should never ever have happened.

I realize I could setup some kind of watcher that runs and force close the Saga, but besides being a bit bloat, it seems somehow one of the more basic guarantees wasn't met, rendering it quite dangerous.

**Comment by MarcinHoppe** [comment] 2016-08-23 12:02
At first glance it looks like the TimeoutManager fails to dispatch timeouts requested by the saga. This would explain your symptoms.

I will dig deeper about why this might be happening and if the connection pool problems are the cause or the effect of the problem.

**Comment by tmasternak** [comment] 2016-08-29 11:18
@janpieterz Two potential scenarios in which your saga would not receive the timeout would be:
 * The message gets stuck in .Timeout or TimeoutDispatcher queues that are responsible processing saga timeouts. In such case you should be able to find your missing message one of those,
 * The timeout message processing failed during processing however was successfully moved to error queue. This is less likely as moving to error queue means message processing which will be hindered by connection pool being exhausted as well. In such case your missing message would end up in error queue.

In either case this should not lead to message loss.

**Comment by janpieterz** [comment] 2016-08-29 11:22
@tmasternak Thanks for looking into it. I think that part of the issue is also 'solved', if it ever occurs again I'll be making 100% sure to pull a database backup right then to be able to trace what has happened and dig into the errors. There was some database shuffling so we possibly lost a message in an error queue there.

**Comment by janpieterz** [comment] 2016-08-29 11:24
Using the fix provided in https://github.com/Particular/NServiceBus/issues/4089 (manually) this is solved. I'll leave it up to you guys to decide if/when to close the issue. From my point of view, it is solved. Thanks for the help @tmasternak and @MarcinHoppe in this investigation.

**Comment by tmasternak** [comment] 2016-08-29 11:35
@janpieterz happy we could help :).

**Closed by tmasternak** 2016-08-29 11:35 UTC
