### ISSUE TITLE
Possible small memory leak

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/NServiceBus.SqlServer#90] opened 2015-09-17 03:29 UTC
### Symptoms

<img width="428" alt="sql transport before" src="https://cloud.githubusercontent.com/assets/163318/9924133/f45ad068-5cfc-11e5-852c-f9850559b26e.png">

After a couple of hours:

<img width="379" alt="sql transport after" src="https://cloud.githubusercontent.com/assets/163318/9924132/f458f9fa-5cfc-11e5-9a39-41542be413bb.png">

Using gcServer and 64bit after +3.000.000 messages

![Using gcServer and 64bit memory usage](https://www.dropbox.com/s/zu45pjggdvnjep8/Screenshot%202015-09-17%2016.23.07.png?raw=1)

Dumps do not seem to indicate a memory leak in the .net memory space.

### Who's affected

All users

**Comment by SzymonPobiega** [comment] 2015-09-17 03:31
@ramonsmits here's the memory leak issue

**Comment by ramonsmits** [comment] 2015-09-17 11:53
I've made a stress test, you see the rising saw tooth during the first hour and after that it seems to stabilize on my machine (8GB VM, Win10, net 4.6). Created a baseline dump and after an hour again and compared the objects. There was no object count that was indicated a memory leak.

When using the server garbage collector then memory consumption is different. Private bytes goes to around 90MB and seems more stable.

Using server gc and running the process as 64bit instead of 32bit results in much more memory being allocated, +450MB in a few seconds. I will let this run for a long period too and diff the memory dumps and see if there are notable differences .

**Comment by ramonsmits** [comment] 2015-09-17 14:27
Updated description with memory usage on gcServer and x64. Memory dumps do not indicate a memory leak.

**Comment by danielmarbach** [comment] 2015-09-18 08:56
Can we close it then?

**Comment by SzymonPobiega** [comment] 2015-09-18 09:06
your wish is my command @danielmarbach

**Comment by ramonsmits** [comment] 2015-09-18 18:07
It seems to be related to this:

- https://stackoverflow.com/questions/30029462/net-tpl-cancellationtoken-memory-leak

I received dumps from the customer that do indicate a memory leak.

We both run a sample project and on my VM with framework v4.6 I don't have it. Customer is on 4.5.2 so maybe it is a bug in .net framework

**Comment by ramonsmits** [comment] 2015-09-22 10:09
I can reproduce this currently on a VM:

- Azure VM A3
- Windows 2012 R2
- .NET Framework 4.5.1


Following it a screenshot of the delta between two memory dumps:

![Dump delta](https://www.dropbox.com/s/7k5qsytwdeaix8n/Screenshot%202015-09-22%2011.29.30.png?raw=1)

**Comment by ramonsmits** [comment] 2015-09-22 11:11
Using the following branch resolves the memory leak:

- https://github.com/ramonsmits/NServiceBus.SqlServer/tree/hotfix-2.1.4


![adsasd](https://www.dropbox.com/s/blygwuv7fnkszw0/Screenshot%202015-09-22%2012.56.27.png?raw=1)

This fix is based on the following stackoverflow article:

- https://stackoverflow.com/questions/30029462/net-tpl-cancellationtoken-memory-leak


The article describes a similar `ContinueWith` continuation as the SQL Transport.


Not reproducible on Win 10 +  Framework 4.6

**Comment by SzymonPobiega** [comment] 2015-09-22 11:14
Awesome job @ramonsmits !

**Comment by danielmarbach** [comment] 2015-09-22 11:44
What if you have 4.5.2?

-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*

**Comment by ramonsmits** [comment] 2015-09-22 11:45
@danielmarbach v4.5.2 also has the memory leak which is the version that the customer is using.

**Closed** 2015-09-22 11:47 UTC
Labels: Type: Bug

**Comment by danielmarbach** [comment] 2015-09-22 11:50
I'm going to check the core code. In nost cases we are fine because we
don't want the task to transition to canceled state (i.ex. Message pump)
there we don't pass the token to the task continuation

-- 
*#NSBcon 2015 • The "All About NServiceBus" conference is back *
*• Learn more <http://go.particular.net/l/27442/2015-08-21/5d4wzp> →*
