### ISSUE TITLE
Endpoint instance crashed on Timeout exception on QueuePeeker (3.1.3)

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#420] opened 2017-12-18 10:23 UTC
I got the following exception and the endpoint instance immediately crashed. I don't think that should happen.

```
2017-12-18 11:18:08.137 FATAL NServiceBus Failed to peek Transport.LedgerGateway@[dbo]@[bus]
System.Data.SqlClient.SqlException (0x80131904): Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): The wait operation timed out
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.SqlCommand.InternalEndExecuteReader(IAsyncResult asyncResult, String endMethod, Boolean isInternal)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderInternal(IAsyncResult asyncResult)
   at System.Data.SqlClient.SqlCommand.EndExecuteReaderAsync(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.TableBasedQueue.<TryPeek>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.QueuePeeker.<Peek>d__1.MoveNext()
ClientConnectionId:3b24fcff-01d1-44ed-828b-3dfb6e2a9b61
Error Number:-2,State:0,Class:11

**Comment by MarcinHoppe** [comment] 2017-12-18 10:53
@ramonsmits Can you post more information? How is the endpoint configured? Is there a critical action configured?

**Comment by SzymonPobiega** [comment] 2017-12-18 11:52
👆 what @MarcinHoppe said. Looking at https://github.com/Particular/NServiceBus.SqlServer/blob/3.1.3/src/NServiceBus.SqlServer/Receiving/QueuePeeker.cs#L52 the exceptions are passed through a circuit breaker.

Here's the circuit breaker setup code https://github.com/Particular/NServiceBus.SqlServer/blob/3.1.3/src/NServiceBus.SqlServer/Receiving/MessagePump.cs#L28

**Comment by ramonsmits** [comment] 2017-12-18 12:36
@MarcinHoppe @SzymonPobiega Yes, I have a critical error callback configured:

``` 
        cfg.DefineCriticalErrorAction(ctx =>
        {
            Environment.FailFast("NServiceBus CriticalError", ctx.Exception);
            return Task.CompletedTask;
        });
``` 

However, I didn't see any info in the FATAL that the circuit breaker was activated. It seems that the error is based on the following message:

https://github.com/Particular/NServiceBus.SqlServer/blob/3.1.3/src/NServiceBus.SqlServer/Receiving/MessagePump.cs#L28

I do not see anything mentioning the circuit breaker in the error to that is why I assumed this was not caused via the circuit breaker.

I had log level set to ERROR and up, so that is maybe why I didn't see any circuit breaker

**Comment by SzymonPobiega** [comment] 2018-01-08 11:46
@ramonsmits what should be the next steps here?

**Comment by shoffman11** [comment] 2018-07-19 17:15
I am experiencing the same issue starting an endpoint instance that was stopped for a couple days while the processes that send to it kept running.  The endpoint instance starts up, but then fails while running the QueuePeeker for 30 seconds which appears to be the default timeout for the peek.

In my case, the messaging table in the database has ~5.1 million records now (and continuing to grow because the senders are not stopped).  Executing the peek query manually in SQL Server Management Studio takes about 50 seconds to 1 minute, even after rebuilding the indexes on the table.  I have the latest recommended indexes from the installer (clustered on RowVersion, non-clustered filtered on Expires).

NServiceBus 6.4.4
NServiceBus.Host 7.0.2
NServiceBus.Persistence.Sql 3.1.0
NServiceBus.SqlServer 3.1.4

I did not any settings in the documentation to override this query timeout value.

Suggest adding a way to allow users to override the query timeout so the endpoint can be started successfully when there is a huge backlog, or some how optimize the peek operation.

![image](https://user-images.githubusercontent.com/16502526/42958922-07efd504-8b55-11e8-8f51-f801065392cf.png)

**Comment by tmasternak** [comment] 2018-07-20 08:04
@shoffman11 currently there is not way to change `CommandTimeout` for `QueuePeeker` - as you mentioned this is the root cause of the behavior that you are seeing. 

I think that it's going to be most effective to handle your particular case as a support cast. Could you please send an email to support@particular.net so we can handle it from there?

/cc: @weralabaj

**Comment by SzymonPobiega** [comment] 2020-05-04 14:22
This has been fixed on 4.x and later and will be fixed for 3.x as part of https://github.com/Particular/NServiceBus.SqlServer/issues/605

**Closed by SzymonPobiega** 2020-05-04 14:22 UTC
