### ISSUE TITLE
Receiving concurrently more than Default Max Pool Size of messages results in exception.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#204] opened 2016-04-19 11:55 UTC
## Reproduction

In V3 of the transport when sending and/or receiving more than 100 (which is default size of SqlConnection pool) messages concurrently the connection pool size reaches it's limit which results in exceptions being thrown.

## PoA

* [x] When connection string is configured via `ConnectionString` during initialization of the transport check if `Max Pool Size` is set or if pooling is disabled and if not we log a WARN and direct to doco.
* [x] When connection is provided with registered callback do a one-time check similar to above and if needed log a WARN

**Comment by tmasternak** [comment] 2016-04-20 11:45
I think that we need to clearly define a goal when resolving this one. I think we can do only best-effort approach. Here are some reasons
 * We are able to figure out only the configured limit for receiving. `ConcurrencyLimit` does not prevent users from sending more messages concurrently outside of handler
 * We are able to do only the guestimation to check if the MaxPoolSize has a proper value. For example if  concurrency is 100 and each receive sends message as isolated dispatches s/he will need ~200 open connections. There are also other factors to consider such as custom-checks, business data sql connections and execution environment in general.

I would propose to
 * Log `WARN` whenever user does not specify the MaxPoolSize option (this does not cover custom connection factory though)
 * Consider providing better [documentation](http://docs.particular.net/nservicebus/sqlserver/configuration#connection-strings) regarding how to arrive at proper pool size

**Comment by HEskandari** [comment] 2016-09-05 04:04
What is the scope of this? Should it be backported to v2 as well?

**Comment by tmasternak** [comment] 2016-09-05 07:14
@HEskandari this is v3 only issue. The reason is that by default in v5 of core concurrency limit is set to 1 which makes running out of connections impossible. With v6  concurrency limit defaulting to 100 the possibility of that happening **was** quite  big. The default has been [changed](https://github.com/Particular/NServiceBus/issues/4089) to be Max(2, LogicalProcessorCount).

That being said the scope of the issue is to put a warning just as it said in description. Please disregard my later comment https://github.com/Particular/NServiceBus.SqlServer/issues/204#issuecomment-212392885.

**Comment by HEskandari** [comment] 2016-09-06 02:14
Think we should also update all the connection strings in the snippets on [this page](http://docs.particular.net/nservicebus/sqlserver/connection-settings) to give people reading the doco the right impression. 

Should I add it to the PoA?

**Comment by SzymonPobiega** [comment] 2016-09-06 04:37
:+1: for adding pool size to all connection strings in context of sql transport.

**Comment by tmasternak** [comment] 2016-09-06 06:31
> Also about checking the connection generated via Factory, since the return type of current API is a Task, to do this, we'll need to generate a connection at startup to perform this check. Not sure if that is the right approach.

I don't think it is a must to generate the warning at startup. As long as we put something in the log we should be good. In other words I think that putting the one-time check in `OpenNewConnection` of SqlConnectionFactory is good enough.

**Comment by HEskandari** [comment] 2016-09-07 03:58
@Particular/sqlserver-transport-maintainers The PR for docs changes is also submitted. Is there anything else left to do?

**Comment by tmasternak** [comment] 2016-09-07 08:30
@HEskandari all is done here :+1: . Closing

**Closed by tmasternak** 2016-09-07 08:30 UTC
Labels: Tag: Maintainer Prio, Tag: Triaged, Type: Bug
