### ISSUE TITLE
Evaluate In-Memory OLTP

### ISSUE THREAD

**Issue by tmasternak** [Particular/NServiceBus.SqlServer#235] opened 2016-05-17 09:06 UTC
Let's figure out if we can take advantage of `In-Memory OLTP` feature in `SqlServer` transport. We should probably check if:
 * Transport runs correctly on top of `In-Memory OLTP`
 * We get some performance gains
 * The behavior is the same on `Azure` and `On-premise`

**Comment by MarcinHoppe** [comment] 2016-09-22 11:31
Duplicate of #265

**Closed by MarcinHoppe** 2016-09-22 11:31 UTC
Labels: Type: Spike
