### ISSUE TITLE
Exception when connecting to SQL Server at startup are swallowed and generic error message is returned

### ISSUE THREAD

**Issue by alexander-kucherov** [Particular/NServiceBus.SqlServer#488] opened 2019-05-22 12:26 UTC
Netcore 2.2 application raises NotSupportedException ('The keyword 'Network Library' is not supported on this platform, prefix the 'Data Source' with the protocol desired instead ('tcp:' for a TCP connection, or 'np:' for a Named Pipe connection).')
in SqlConnectionStringBuilder when I use Network Library=dbmssocn parameter in the connection string.

SqlServerTransportInfrastructure.CheckForAmbientTransactionEnlistmentSupport catches NotSupportedException and thinks that (The version of System.Data.SqlClient in use does not support enlisting SQL connections in ambient transactions.)
```csharp
                try
                {
                    using (var scope = new TransactionScope(TransactionScopeOption.RequiresNew, transactionOptions, TransactionScopeAsyncFlowOption.Enabled))
                    using (await connectionFactory.OpenNewConnection().ConfigureAwait(false))
                    {
                        scope.Complete();
                    }
                }
                catch (NotSupportedException)
                {
                    var message = "The version of System.Data.SqlClient in use does not support enlisting SQL connections in ambient transactions, so the TransactionScope transport transaction mode cannot be used. Use `EndpointConfiguration.UseTransport<SqlServerTransport>().Transactions` to select a different transport transaction mode.";
                    return StartupCheckResult.Failed(message);
                }
```
In this case an original exception was lost and finding an original problem is very difficult.

Sample Code
```csharp
var connectionString = "Data Source=localhost;Initial Catalog=mydb;Network Library=dbmssocn;Integrated Security=SSPI;Application Name=NsbApplication;";
var endpointConfiguration = new EndpointConfiguration("My Endpoint");
endpointConfiguration.UseTransport<SqlServerTransport>()
	.ConnectionString(connectionString)
	.TransactionScopeOptions(TimeSpan.FromMinutes(1), IsolationLevel.ReadCommitted)
	.Transactions(TransportTransactionMode.TransactionScope);
endpointConfiguration.DisableFeature<TimeoutManager>();
endpointConfiguration.DisableFeature<MessageDrivenSubscriptions>();
await Endpoint.Start(endpointConfiguration);```

**Comment by WojcikMike** [comment] 2019-05-28 09:33
Hi @alexander-kucherov thanks for raising this bug with us. 

We triaged it and see it important to be fixed in the near future. Due to that, it is on our list of items to be fixed. The implementation of that bugfix and release of it should happen within the next few weeks. More details will be provided when this issue will be picked up.

**Comment by SzymonPobiega** [comment] 2019-06-12 08:19
Fixed in #491

**Closed by SzymonPobiega** 2019-06-12 08:19 UTC
Labels: Bug

**Comment by SzymonPobiega** [comment] 2019-06-12 08:24
@alexander-kucherov the issue is fixed and I am in the process of releasing it. I'll ping you when done.

**Comment by SzymonPobiega** [comment] 2019-06-12 13:37
@alexander-kucherov 4.1.3 released
