### ISSUE TITLE
Message pump does not handle connection timeouts and or connection limits

### ISSUE THREAD

**Issue by ramonsmits** [Particular/NServiceBus.SqlServer#409] opened 2017-11-04 16:36 UTC
When you have scaled out your endpoint it can happen that you either reach the database its connection limit or you will not get a connection from the connection pool. In such cases the message pump seems to fail immediately with core v6. It seems to keep running on core v7.

When the database has reached its limits:

> NServiceBus.Transport.SQLServer.MessagePump|Sql receive operation failedResource ID : 1. The request limit for the database is 30 and has been reached. See 'http://go.microsoft.com/fwlink/?LinkId=267637' for assistance.

When the connection pool is depleted and a connection timeout occurs:

>NServiceBus.Transport.SQLServer.MessagePump|Sql receive operation failedTimeout expired.  The timeout period elapsed prior to obtaining a connection from the pool.  This may have occurred because all pooled connections were in use and max pool size was reached.

Setting the pool size to a very low value and increasing the connection timeout duration seem to be resulting in a sort of 'deadlock' in the task scheduler.

**Comment by SzymonPobiega** [comment] 2017-11-04 17:51
Isn't this caused by different handling of critical action in 7 versus 6?

**Comment by andreasohlund** [comment] 2017-11-06 07:36
>Isn't this caused by different handling of critical action in 7 versus 6?

@ramonsmits does the transport missbehave in any way while the error condition persists? Does it recover properly once connections become available as well?

**Comment by andreasohlund** [comment] 2017-11-06 14:29
Had a call with @ramonsmits and @MarcinHoppe and we decided that @ramonsmits will verify the following:

* That v7 resumes normal operations once there are connections available as well
* That v7 behaves properly while the failure is happening, CPU Churn, Memory , Excessive logging etc

**Comment by ramonsmits** [comment] 2017-11-07 12:43
@MarcinHoppe @andreasohlund 

In v7:

- If no critical error callback is specified, the endpoint remains running and recovers once database is available again.
- If a critical error callback is specified, the endpoints seems to trigger the critical error call after about 20seconds. The doco states that should be 2 minutes: https://docs.particular.net/transports/sql/connection-settings?version=sqltransport_4#circuit-breaker-wait-time
- Circuit breaker is continuously armed/disarmed because connections can become (un)available.
- Message pump delay doesn't seem to be applied when calling `NServiceBus.Transport.SQLServer.SqlConnectionFactory.OpenNewConnection`, see the following exception.
- There is no excessive CPU or RAM usage
- Excessive logging is occurring with log level WARN, especially when the maximum concurrency level is set to a high value.
  - An alternative approach, count the attempts and report every 5 seconds how long the last successful peek/receive happened so then you would see WARN every 5 seconds stating. This would not flood the log with 50 exceptions every second if maximum concurrency is set to 50.
    - > Last successful peak/receive at 13:39:03 (00:04:13 ago), 80 attempts since previous. Next status update after 00:00:05.


## NServiceBus.Transport.SQLServer.SqlConnectionFactory.OpenNewConnection - SqlException
```
2017-11-07 10:59:18.5798|WARN|18|NServiceBus.Transport.SQLServer.MessagePump|Sql receive operation failed
System.Data.SqlClient.SqlException (0x80131904): A connection was successfully established with the server, but then an error occurred during the pre-login handshake. (provider: Shared Memory Provider, error: 0 - No process is on the other end of the pipe.) ---> System.ComponentModel.Win32Exception (0x80004005): No process is on the other end of the pipe
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<>c__DisplayClass2_0.<<Default>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.SqlConnectionFactory.<OpenNewConnection>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.ProcessWithTransactionScope.<ReceiveMessage>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Transport.SQLServer.MessagePump.<InnerReceive>d__6.MoveNext()
```

**Comment by andreasohlund** [comment] 2017-11-07 13:07
@Particular/sqlserver-transport-maintainers I'd say we should treat the logging fix as a must for v4?

**Comment by MarcinHoppe** [comment] 2017-11-07 13:18
That was my thinking as well. /cc @SzymonPobiega @tmasternak

**Comment by andreasohlund** [comment] 2017-11-07 19:11
@ramonsmits are you ok with treating the logging fix as a must? (anything else that you believe should be fixed for v4?)

**Comment by andreasohlund** [comment] 2017-11-07 19:12
Side note, the title on this one is way off. Perhaps raise a dedicated issue for the logging and close this one?

**Comment by MarcinHoppe** [comment] 2017-11-08 08:44
@ramonsmits @andreasohlund Closing this in favor of #411.

/cc @Particular/sqlserver-transport-maintainers

**Closed by MarcinHoppe** 2017-11-08 08:44 UTC
